name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'feature/*'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          context: bootloader
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=./out
